import cv2
import os
import config

class MockDrone:
    def __init__(self, detector):
        self.detector = detector
        self.folder = config.DRONE_IMG_PATH
        
        valid_exts = (".jpg", ".jpeg", ".png", ".bmp", ".webp")
        if os.path.exists(self.folder):
            self.images = sorted([
                f for f in os.listdir(self.folder)
                if f.lower().endswith(valid_exts)
            ])
        else:
            self.images = []
        self.current_index = 0

    def scan(self):
        # 1. Safety check
        if not self.images or self.current_index >= len(self.images):
            return [], -1 

        # 2. Load Image
        filename = self.images[self.current_index]
        img_path = os.path.join(self.folder, filename)
        image = cv2.imread(img_path)

        if image is None:
            self.current_index += 1
            return [], self.current_index

        if image.shape[2] == 4:
            image = cv2.cvtColor(image, cv2.COLOR_BGRA2BGR)

        # 3. Run detection
        # The detector returns a list of dicts containing BOTH:
        # - "raw_image": The clean base64 image
        # - "image": The boxed base64 image (generated by YOLO)
        detections = self.detector.detect(image, source="drone") 

        scanned_index = self.current_index
        self.current_index += 1
        
        return detections, scanned_index